vcpu_count: 8
memory_size: 16384
cpu_pinning:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
isolated_cores: 0-7
vm_name: my-vm
vm_disk_path: /var/lib/libvirt/images/my-vm.qcow2
backup_vm_disk_path: /var/lib/libvirt/images/my-vm-bak.qcow2
vm_image_url: https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2
vm_user: root
vm_password: ansible_password
ssh_key_path: /tmp/vm_ssh_key.pub
cloud_init_config_path: /var/lib/libvirt/images/cloud_init_config.yml
