---
- name: Install KVM and create VM
  block:
    - name: Install libvirt packages
      yum:
        name:
          - libvirt
          - qemu-kvm
          - virt-install
          - qemu-img
          - cloud-init
          - guestfs-tools
          - python3-libvirt
        state: present

    - name: pip install lxml
      pip:
        name: lxml
        executable: pip3

    - name: Start and enable libvirtd service
      service:
        name: libvirtd
        state: started
        enabled: yes

    - name: Create storage directory
      file:
        path: /var/lib/libvirt/images
        state: directory
        owner: qemu
        group: qemu
        mode: '0755'

    - name: Check if CentOS Stream 9 image exists
      stat:
        path: "{{ backup_vm_disk_path }}"
      register: image_stat

    - name: Download CentOS Stream 9 image
      get_url:
        url: "{{ vm_image_url }}"
        dest: "{{ backup_vm_disk_path }}"
      when: not image_stat.stat.exists

    - name: Copy the backup vm disk to become the VM disk
      command: cp "{{ backup_vm_disk_path }}" "{{ vm_disk_path }}"

    - name: resize image to 200G
      command: qemu-img resize "{{ vm_disk_path }}" +200G

    - name: Generate SSH key pair
      community.crypto.openssh_keypair:
        path: /tmp/vm_ssh_key
        type: rsa
        size: 2048
        state: present
      register: ssh_key

    - name: Save the public key into a file
      copy:
        content: "{{ ssh_key.public_key }}"
        dest: "{{ ssh_key_path }}"

    - name: Create cloud-init config
      template:
        src: cloud_init_config.yml.j2
        dest: "{{ cloud_init_config_path }}"
      vars:
        vm_ssh_public_key: "{{ ssh_key.public_key }}"

    - name: Use virt-customize to inject ssh key
      command: >
        virt-customize -a "{{ vm_disk_path }}" --hostname {{ vm_name }} --selinux-relabel 
        --root-password password:{{ vm_password }} --ssh-inject 'root:file:{{ ssh_key_path }}'
        --upload "{{ cloud_init_config_path }}":/tmp/user-data --upload /tmp/meta-data:/tmp/meta-data --run /tmp/cloud-init-script.sh

    - name: Use virt-customize to fdisk to resize disk
      command: >
        virt-customize -a "{{ vm_disk_path }}" --run-command 'echo -e "d\nn\np\n1\n\n\nw" | fdisk /dev/sda'

    - name: Create a VM
      community.libvirt.virt:
        name: "{{ vm_name }}"
        command: define
        xml: "{{ lookup('template', 'vm_template.xml.j2') }}"
        uri: qemu:///system

    - name: Start the VM
      community.libvirt.virt:
        name: "{{ vm_name }}"
        state: running
        uri: qemu:///system

    - name: Sleep 30 seconds to allow the VM to boot
      pause:
        seconds: 30

    - name: Get the VM IP address using virsh domifaddr
      shell: virsh -c qemu:///system domifaddr {{ vm_name }} | grep ipv4 | awk '{print $4}' | cut -d'/' -f1
      register: domifaddr_output

    - name: Parse the VM IP address
      set_fact:
        vm_ip: "{{ domifaddr_output.stdout }}"

    - name: Display the VM IP address
      debug:
        msg: "The IP address of the VM is {{ vm_ip }}"

    - name: Wait for VM to be reachable
      ansible.builtin.wait_for:
        host: "{{ vm_ip }}"
        port: 22
        delay: 10
        timeout: 60
      register: vm_reachable

    - name: Test the connection to the VM
      delegate_to: "{{ vm_ip }}"
      vars:
        ansible_user: "{{ vm_user }}"
        ansible_ssh_private_key_file: /tmp/vm_ssh_key
        ansible_ssh_retries: 5
      block:
        - name: Test the connection to the VM
          command: uname -a
          register: host_output

        - name: Display the output of the command
          debug:
            msg: "The output of the command is {{ host_output.stdout }}"

    - name: Add or replace VM name into /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ vm_ip }} {{ vm_name }}"
        create: yes

    - name: Test ssh to the VM by ssh to the VM by name
      ansible.builtin.wait_for:
        host: "{{ vm_name }}"
        port: 22
        delay: 10
        timeout: 60
      register: ssh_reachable 

  rescue:
    - name: Destroy the VM
      community.libvirt.virt:
        name: "{{ vm_name }}"
        state: destroy
        uri: qemu:///system

    - name: Undefine the VM
      community.libvirt.virt:
        name: "{{ vm_name }}"
        state: absent
        uri: qemu:///system

    - name: Fail the playbook
      fail:
        msg: "An error occurred during the playbook execution. The VM and its associated resources have been cleaned up."
