---
- name: Deploy and run the Kepler Validator
  hosts: localhost
  become: yes
  vars:
    validator_repo: "https://github.com/sustainable-computing-io/kepler.git"
    validator_dir: "/opt/kepler/e2e/tools/validator/src"
    validator_yaml_path: "/opt/kepler/e2e/tools/validator/src/validator.yaml"
    stress_test_script_path: "/opt/kepler/e2e/tools/validator/scripts/stress_test.sh"
    query_json_path: "/opt/kepler/e2e/tools/validator/query.json"

  tasks:
    - name: yum install stress-ng, git and python3.11
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - python3.11
        - python3.11-pip
        - stress-ng

    - name: Clone the Kepler repository
      git:
        repo: "{{ validator_repo }}"
        dest: "/opt/kepler"
        version: main
        force: yes

    - name: Create validator.yaml
      copy:
        dest: "{{ validator_yaml_path }}"
        content: |
          remote:
            host: my-vm
            username: root
            pkey: /tmp/vm_ssh_key

          metal:
            vm:
              name: my-vm

          prometheus:
            url: http://localhost:9090
            interval: 300s
            steps: 30s

          query_path: ../query.json

    - name: Create stress test script
      copy:
        dest: "{{ stress_test_script_path }}"
        content: |
          #!/bin/bash
           for level in $(seq 10 10 100); do
              echo "Stress level: $level"
              stress-ng --cpu $(nproc) --cpu-load $level --timeout 10s
          done

    - name: Create query.json
      copy:
        dest: "{{ query_json_path }}"
        content: |
          {% raw %}
          [
              {
                  "expected_query": "sum(rate(kepler_{level}_package_joules_total{{{query}}}[{interval}]))",
                  "actual_query": "sum(rate(kepler_node_package_joules_total[{interval}]))"
              },
              {
                  "expected_query": "sum(rate(kepler_{level}_platform_joules_total{{{query}}}[{interval}]))",
                  "actual_query": "sum(rate(kepler_node_platform_joules_total[{interval}]))"
              }
          ]
          {% endraw %}

    - name: Make stress test script executable
      file:
        path: "{{ stress_test_script_path }}"
        mode: '0755'

    - name: Install the validator
      shell: |
        cd {{ validator_dir }}
        pip3.11 install ..

    - name: Run the validator
      shell: |
        cd {{ validator_dir }}
        PYTHONPATH=${PYTHONPATH}:./ python3.11 validator/__main__.py stress -s {{ stress_test_script_path }}
      args:
        chdir: "{{ validator_dir }}"
