---
- name: Configure SSH tunnel using systemd
  hosts: ssh_tunnel_server
  become: yes

  tasks:
    - name: Create systemd service file for SSH tunnel
      copy:
        dest: "{{ systemd_service_path }}"
        content: |
          [Unit]
          Description=SSH Tunnel to Kepler Exporter in VM
          After=network.target

          [Service]
          ExecStart=/usr/bin/ssh -N -i {{ ssh_key_path }} -L {{ local_port }}:localhost:{{ remote_port }} {{ ssh_tunnel_user }}@{{ ssh_tunnel_vm }}
          User={{ ssh_tunnel_user }}
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable SSH tunnel systemd service
      systemd:
        name: "{{ ssh_tunnel_service_name }}"
        enabled: yes
        state: started

    - name: Check Prometheus metrics query
      shell: curl -s http://localhost:9090/api/v1/query?query=kepler_node_package_joules_total
      register: prometheus_output


    - name: Debug Prometheus output
      debug:
        var: prometheus_output.stdout