name: Equinix Metal Trainer

on:
  workflow_dispatch:
  workflow_call:

permissions:
  pull-requests: write
  contents: write
  repository-projects: write
  packages: write

jobs:
  Create-runner:
    name: "Create Runner"
    runs-on: ubuntu-latest

    steps:
      - name: metal-runner-action
        uses: equinix-labs/metal-runner-action@v0.3.0
        with:
          github_token: ${{ secrets.GH_SELF_HOSTED_RUNNER_TOKEN }}
          metal_auth_token: ${{ secrets.EQUINIX_API_TOKEN }}
          metal_project_id: ${{ secrets.EQUINIX_PROJECT_ID }}
          metro: "da"
          plan: "c3.small.x86"
          os: "rhel_9"

  Train-models:
    name: "Train Models"
    needs: Create-runner
    runs-on: self-hosted
    continue-on-error: true
    outputs:
      runner-name: ${{ runner.name }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Setup Runner Action
        uses: ./.github/actions/setup-action

      - name: Run Trainer Action
        uses: ./.github/actions/train-action
        with:
          model_export_path: /tmp/trained-equinix-models

      # - name: Archive Models
      #   run: tar -czf trained-equinix-models.tar.gz /refined-models/

      - name: Upload models as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: trained-equinix-models
          path: /tmp/trained-equinix-models
          retention-days: 2

  Cleanup:
    name: "Cleanup"
    runs-on: ubuntu-latest
    needs: [Train-models]

    steps:
      - name: delete runner
        uses: rootfs/metal-delete-action@main
        with:
          authToken: ${{ secrets.EQUINIX_API_TOKEN }}
          projectID: ${{ secrets.EQUINIX_PROJECT_ID }}
          runnerName: ${{ needs.Train-models.outputs.runner-name }}