name: Equinix Metal with kepler Action

on:
  workflow_dispatch:

jobs:
  Create-runner:
    name: "Create Runner"
    uses: ./.github/workflows/create_equinix_runner.yml
    secrets: inherit

  Install:
    name: "Install"
    needs: Create-runner
    runs-on: self-hosted
    continue-on-error: true
    outputs:
      runner-name: ${{ runner.name }}

    steps:
      - name: Setup runner
        run: |
          sudo yum -y install git
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/bin/
          which kind
          curl -LO https://dl.k8s.io/release/v1.25.4/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/bin/
          which kubectl
          
      - name: use Kepler action to deploy cluster
        uses: sustainable-computing-io/kepler-action@main
        with:
          install_containerruntime: true
          cluster_provider: kind
          restartcontianerruntime: true
          local_path: /usr/bin/

  Cleanup:
    name: "Cleanup"
    needs: [Install]
    uses: ./.github/workflows/clean_equinix_runner.yml
    secrets: inherit
    with:
      runner_name: ${{ needs.Install.outputs.runner-name }}
